add post build smoke test

diff --git a/.github/workflows/template_build_deploy.yml b/.github/workflows/template_build_deploy.yml
--- a/.github/workflows/template_build_deploy.yml
+++ b/.github/workflows/template_build_deploy.yml
@@ -1,5 +1,5 @@
 ---
-name: template - build and deploy
+name: template - build, test and deploy
 
 on:
   workflow_call:
@@ -26,6 +26,7 @@ env:
   REGISTRY_USERNAME: ${{ vars.DOCKER_USERNAME != '' && vars.DOCKER_USERNAME || github.actor }}
   REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD != '' && secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}
   REPOSITORY: ${{ vars.DOCKER_REPOSITORY != '' && vars.DOCKER_REPOSITORY || github.repository }}
+  BOLT_GEM: 1
 
 jobs:
   select:
@@ -100,7 +101,7 @@ jobs:
     permissions:
       contents: read
       packages: write
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     strategy:
       max-parallel: 10
       fail-fast: false
@@ -153,7 +154,42 @@ jobs:
         run: |
           docker build --rm --no-cache -t ${IMAGE_TAG} . --label "base_image=${BASE_ID}" -f ${{ matrix.dockerfile }}.dockerfile --build-arg BASE_IMAGE_TAG=${{ matrix.base_tag }} --build-arg OS_TYPE=${{ matrix.base_image }}
 
-      - if: steps.build_image.conclusion == 'success'  && needs.select.outputs.push == 'true'
+      - name: Smoke test setup
+        id: test_ruby_setup
+        uses: "ruby/setup-ruby@v1"
+        with:
+          ruby-version: '3.2'
+          bundler-cache: true
+          working-directory: tests/smoke
+
+      - name: Smoke test provision
+        id: test_image
+        continue-on-error: true
+        working-directory: tests/smoke
+        timeout-minutes: 1
+        run: |
+          bundle exec bolt module install
+          bundle exec rake litmus:provision[docker,${IMAGE_TAG}]
+          bundle exec bolt command run 'last' -t all
+
+        # Previous step should always continue on error
+        # so docker logs will be added to the output
+      - name: Smoke test cleanup
+        if: steps.test_image.conclusion == 'success'
+        working-directory: tests/smoke
+        run: |
+          set +e
+          echo ::group::Bolt inventory
+          bundle exec bolt inventory show --detail
+          echo ::endgroup::
+          for x in `docker ps -a --format '{{.ID}}'` ; do
+            docker logs ${x}
+          done
+          bundle exec rake litmus:tear_down
+          # ALWAYS exit based on the outcode of the smoke test provision
+          exit ${{ steps.test_image.outcome != 'success' && '1' || '0' }}
+
+      - if: steps.test_image.outcome == 'success' && needs.select.outputs.push == 'true'
         name: Push ${{ matrix.image_tag }} to ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
         run: |
           docker image push $IMAGE_TAG
